name: DevOpsGitAction

on:
  push:
    branches:
      - main

jobs:
  Show-name:
    runs-on: ubuntu-latest
    
    steps:
    - name: checkout
      uses: actions/checkout@v2
      
    - name: Launch image&script
      run: |
        docker run --rm ubuntu bash -c 'echo "My First Name: Andrii" && echo "My Last Name: Baranov"'
